#!/bin/sh
#
# Copyright (C) 2025 Pedro Alves
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Wrapper commit-msg hook that runs multiple commit message checkers.

set -eu

hookdir=$(dirname "$0")

# First the Gerrit hook, verbatim from
# <https://github.com/GerritCodeReview/gerrit/blob/master/resources/com/google/gerrit/server/tools/root/hooks/commit-msg>
# (and renamed).  This runs "git stripspace" which has the side effect
# of normalizing all trailers to "Token: Value" format.  This breaks
# the SPR trailer, which must be "commit-id:UUID", without the space.
"$hookdir/commit-msg.gerrit" "$1"

# Now the SPR hook.  This adds "commit-id: UUID", with the space, if
# it isn't there already.
"$hookdir/commit-msg.spr-commit-id" "$1"

# This finally strips the space from the SPR commit-id trailer.
"$hookdir/commit-msg.spr-fixup" "$1"
